# Explicitly opens up and exposes all actuator endpoints over HTTP web ports
management.endpoints.web.exposure.include=health,info,prometheus

# Ensures the endpoint outputs clean, detailed structural JSON information
management.endpoint.health.show-details=always
