# Expose the health endpoints to the web server interface
management.endpoints.web.exposure.include=health,info,prometheus

# Force detailed JSON output for monitoring tools
management.endpoint.health.show-details=always

# Enable official Spring Boot 3.x Kubernetes probe routing sub-groups
management.health.probes.enabled=true
